---
- name: RHEL AI VM setup
  hosts: control_node
  gather_facts: false
  tasks:
    - name: RHELAI VM setup
      when: deploy_rhelai_enabled | bool
      block:
        - name: Install python-openstackclient
          ansible.builtin.pip:
            name: python-openstackclient
          become: true
          when: deploy_rhelai_openstack_command == "openstack"
        - ansible.builtin.import_tasks: tasks/cleanup_vm.yaml  # noqa: name[missing]
          when: deploy_rhelai_pre_cleanup_enabled | bool
        - ansible.builtin.import_tasks: tasks/deploy_vm.yaml  # noqa: name[missing]

- name: RHEL AI Validation
  hosts: target_nodes
  gather_facts: false
  tasks:
    # Set-up the environment
    - name: Setup
      become: true
      ansible.builtin.import_tasks: tasks/setup.yaml
    - name: Check GPUs
      ansible.builtin.import_tasks: tasks/gpus.yaml
    - name: Check NVIDIA
      ansible.builtin.import_tasks: tasks/nvidia.yaml
    - name: Check iLab
      ansible.builtin.import_tasks: tasks/ilab.yaml
    - name: Cleanup
      become: true
      ansible.builtin.import_tasks: tasks/cleanup.yaml

- name: RHEL AI VM post-cleanup
  hosts: control_node
  gather_facts: false
  tasks:
    - ansible.builtin.import_tasks: tasks/cleanup_vm.yaml  # noqa: name[missing]
      when: deploy_rhelai_enabled | bool and deploy_rhelai_post_cleanup_enabled | bool
