---
- name: Run lspci command and save output
  ansible.builtin.command: lspci -nn
  register: lspci_output
  changed_when: false

- name: Check each PCI device
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ lspci_output.stdout }}" | grep '{{ item.key }}' | wc -l
  register: pci_count
  loop: "{{ pci_devices | dict2items }}"
  vars:
    expected_count: "{{ item.value }}"
  failed_when: pci_count.stdout | int != expected_count | int
  changed_when: false

- name: Set found_nvidia to true if NVIDIA is found
  ansible.builtin.set_fact:
    found_nvidia: true
  when: lspci_output.stdout is search("NVIDIA")
