---
- name: "TEST[gpus] Check if GPUs in Passthrough mode are present in RHEL AI VM (lspci)"
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ lspci_output.stdout }}" | grep '{{ item.key }}' | wc -l
  register: pci_count
  loop: "{{ pci_devices | dict2items }}"
  vars:
    expected_count: "{{ item.value }}"
  failed_when: pci_count.stdout | int != expected_count | int
  changed_when: false
