---
- name: Create VM {{ deploy_rhelai_vm_name }}
  openstack.cloud.server:
    state: present
    name: "{{ deploy_rhelai_vm_name }}"
    flavor: "{{ deploy_rhelai_flavor }}"
    image: "{{ deploy_rhelai_image }}"
    key_name: "{{ deploy_rhelai_key_name }}"
    nics:
      - net-name: "{{ deploy_rhelai_net_name }}"
    floating_ips:
      - "{{ deploy_rhelai_floating_ip }}"
    security_groups:
      - "{{ deploy_rhelai_security_group }}"
    ca_cert: "{{ deploy_rhelai_ca_cert_path }}"

- name: Poll for SSH to be available on {{ deploy_rhelai_vm_name }}
  ansible.builtin.command: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -i {{ deploy_rhelai_private_key_file }} cloud-user@{{ deploy_rhelai_floating_ip }}
  retries: 60  # 60 * 10 = 10 mins
  delay: 10
  register: result
  until: result.rc == 0
  changed_when: false
