---
- name: Setup
  become: true
  ansible.builtin.import_tasks: setup.yaml

- name: Nvidia Setup
  ansible.builtin.include_role:
    name: nvidia_driver
    apply:
      become: true
  vars:
    nvidia_driver_module_version: "latest-dkms"
    nvidia_driver_install_management_library: false


- name: Check GPUs
  ansible.builtin.import_tasks: gpus.yaml
- name: GPUs Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: gpus_assertions.yaml
  ignore_errors: true

- name: Check NVIDIA
  ansible.builtin.import_tasks: nvidia.yaml
- name: NVIDIA Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: nvidia_assertions.yaml
  ignore_errors: true

- name: Check CUDA libs
  ansible.builtin.import_tasks: cuda.yaml
- name: CUDA Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: cuda_assertions.yaml
  ignore_errors: true

- name: Check vllm
  ansible.builtin.import_tasks: vllm.yaml
  when: gpu_validation_model_tests_enabled | bool

- name: Cleanup
  become: true
  ansible.builtin.import_tasks: cleanup.yaml
